### ISSUE TITLE
Nfs client provisioner is deprecated

### ISSUE THREAD

**Issue by rxbn** [projectsyn/component-nfs-client-provisioner#6]
## Context

According to https://github.com/kubernetes-retired/external-storage/tree/master/nfs-client, nfs-client-provisioner is deprecated.

## Alternatives

There is a new replacement for nfs-client-provisioner called nfs-subdir-external-provisioner which is actively maintained: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner

I opened this issue just so you know, maybe you guys can create a new syn component for the subdir provisioner 😃

**Comment by megian** [comment]
There is already a new component based on the nfs-subdir-external-provisioner https://github.com/projectsyn/component-nfs-subdir-external-provisioner.

**Comment by rxbn** [comment]
Oh, I didn't see that. You should probably mark this component as deprecated. But thanks a lot for your answer!

**Comment by megian** [comment]
Resolved via #7 .
